package post;

import java.util.ArrayList;

interface POSTDelegate {
    void userEnteredName(String name);
    void userPressedEnter(Product product, int quantity);
    void userPressedPay(String name, POSTModel.PaymentType paymentType, double amount);
}

public class POSTJFrame extends javax.swing.JFrame {

    POSTDelegate delegate;
    static ProductCatalog cataLog;
    Product product;

    public POSTJFrame() {
        initComponents();
        //displayForm();
        setVisible(true);
    }

    public void setDelegate(POSTDelegate delegate) {
        this.delegate = delegate;
    }
    public void setProductCatalog(ProductCatalog productCatalog) {
    	cataLog = productCatalog;

		}

    public void setQuantityMenuRange(int lowerBound, int upperBound) {
        for (int i = lowerBound; i < upperBound; i++) {
            String quantityOption = Integer.toString(i);
            quantityMenu.add(quantityOption);
        }
    }

    public void updateTotalPrice(Double total) {
        String totalPrice = String.format("%.2f", total);
        totalValueLabel.setText("$ " + totalPrice);
    }

    public void updateInvoiceTextArea(String itemEntry) {
        invoiceTextArea.append(itemEntry);
    }

    public void updateDateLabel() {
        java.util.Date currentDate = new java.util.Date();
        dateLabel.setText(currentDate.toString());
    }

    public void populateUPCMenu(ArrayList<String> upcItems) {
        for (String upcItem : upcItems) {
            upcMenu.add(upcItem);
        }
    }

    public void populatePaymentTypeMenu(String[] items) {
        for (String item : items) {
            paymentTypeMenu.add(item);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainFrame = new javax.swing.JFrame();
        mainPanel = new javax.swing.JPanel();
        invoicePanel = new javax.swing.JPanel();
        invoiceLabel = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        topUnitLabel = new javax.swing.JLabel();
        bottomUnitLabel = new javax.swing.JLabel();
        topExtendedPriceLabel = new javax.swing.JLabel();
        bottomExtendedPriceLabel = new javax.swing.JLabel();
        invoiceTextContainer = new javax.swing.JScrollPane();
        invoiceTextArea = new javax.swing.JTextArea();
        totalLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        itemQuantityLabel = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        enterButton = new java.awt.Button();
        upcMenu = new java.awt.Choice();
        quantityMenu = new java.awt.Choice();
        productQuantityLabel = new javax.swing.JLabel();
        upcLabel = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        paymentTypeMenu = new java.awt.Choice();
        paymentAmountTextField = new java.awt.TextField();
        paymentAmountLabel = new javax.swing.JLabel();
        paymentTypeLabel = new javax.swing.JLabel();
        payButton = new java.awt.Button();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        nameLabel = new java.awt.Label();
        nameTextField = new java.awt.TextField();

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame.getContentPane());
        mainFrame.getContentPane().setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
                mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        mainFrameLayout.setVerticalGroup(
                mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POST");

        invoicePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        invoiceLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        invoiceLabel.setLabelFor(invoicePanel);
        invoiceLabel.setText("Invoice");

        itemLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itemLabel.setText("ITEM");

        topUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        topUnitLabel.setText("UNIT");

        bottomUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bottomUnitLabel.setText("PRICE");

        topExtendedPriceLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        topExtendedPriceLabel.setText("EXTENDED");

        bottomExtendedPriceLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bottomExtendedPriceLabel.setText("PRICE");

        invoiceTextArea.setColumns(20);
        invoiceTextArea.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        invoiceTextArea.setRows(5);
        invoiceTextContainer.setViewportView(invoiceTextArea);

        totalLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalLabel.setText("TOTAL");

        totalValueLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalValueLabel.setText("$");

        itemQuantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itemQuantityLabel.setText("QTY");

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
                invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(invoiceTextContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                                                .addComponent(invoiceLabel)
                                                                .addGap(316, 316, 316))
                                                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(itemLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(itemQuantityLabel)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(topUnitLabel)
                                                        .addComponent(bottomUnitLabel))
                                                .addGap(20, 20, 20)
                                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(topExtendedPriceLabel)
                                                        .addComponent(bottomExtendedPriceLabel))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalValueLabel)
                                .addGap(133, 133, 133))
        );
        invoicePanelLayout.setVerticalGroup(
                invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(invoiceLabel)
                                        .addGroup(invoicePanelLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(topExtendedPriceLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bottomExtendedPriceLabel)
                                                        .addComponent(itemLabel)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(topUnitLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bottomUnitLabel)
                                                        .addComponent(itemQuantityLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invoiceTextContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalValueLabel)
                                        .addComponent(totalLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        enterButton.setLabel("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        productQuantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        productQuantityLabel.setText("Quantity");

        upcLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        upcLabel.setText("UPC");

        productLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        productLabel.setLabelFor(invoicePanel);
        productLabel.setText("Product");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
                productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(productPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(productPanelLayout.createSequentialGroup()
                                                .addComponent(productLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(productPanelLayout.createSequentialGroup()
                                                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(productPanelLayout.createSequentialGroup()
                                                                .addComponent(upcLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(upcMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(productQuantityLabel))
                                                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(quantityMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        productPanelLayout.setVerticalGroup(
                productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanelLayout.createSequentialGroup()
                                .addComponent(productLabel)
                                .addGap(18, 18, 18)
                                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(upcMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(quantityMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(productQuantityLabel)
                                        .addComponent(upcLabel))
                                .addGap(15, 15, 15)
                                .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addContainerGap())
        );

        paymentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        paymentLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        paymentLabel.setLabelFor(invoicePanel);
        paymentLabel.setText("Payment");

        paymentAmountTextField.setBackground(new java.awt.Color(255, 255, 255));
        paymentAmountTextField.setName(" "); // NOI18N
        paymentAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentAmountTextFieldActionPerformed(evt);
            }
        });

        paymentAmountLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        paymentAmountLabel.setText("Paid");

        paymentTypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        paymentTypeLabel.setText("Payment type");

        payButton.setActionCommand("pay");
        payButton.setLabel("PAY");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
                paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(paymentLabel)
                                        .addGroup(paymentPanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(paymentPanelLayout.createSequentialGroup()
                                                                .addComponent(paymentTypeLabel)
                                                                .addGap(8, 8, 8)
                                                                .addComponent(paymentTypeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(paymentAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(paymentAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
                paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(paymentTypeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(paymentPanelLayout.createSequentialGroup()
                                                .addComponent(paymentLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(paymentAmountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                                        .addComponent(paymentAmountTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addComponent(paymentTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        datePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateLabel.setText("Date");

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
                datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        datePanelLayout.setVerticalGroup(
                datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datePanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nameLabel.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.background"));
        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLabel.setText("Customer Name");

        nameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameTextField.setName(" "); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
                customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
                customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(customerPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(invoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(20, 20, 20))))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" Generated Event Handlers">

    private void paymentAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Item added");
        product = cataLog.lookupProduct(upcMenu.getSelectedItem());
        int quantity = Integer.parseInt(quantityMenu.getSelectedItem());
        delegate.userPressedEnter(product,quantity);
        }

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {
        POSTModel.PaymentType paymentType = POSTModel.PaymentType.valueOf(paymentTypeMenu.getSelectedItem());
        if (paymentAmountTextField.getText().isEmpty()) {
            paymentAmountTextField.setText("0.00");
        }
        Double paymentValue = Double.valueOf(paymentAmountTextField.getText());
        delegate.userPressedPay(nameTextField.getText(),paymentType, paymentValue);
    }

    //</editor-fold>

    public static void setLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public static void displayForm() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new POSTJFrame().setVisible(true);
            }
        });
    }

   public static void main(String args[]) {
        setLookAndFeel();
        //displayForm();
    }

    //<editor-fold defaultstate="collapsed" desc=" Private Variables Declaration ">
    // Variables declaration - do not modify
    private javax.swing.JLabel bottomExtendedPriceLabel;
    private javax.swing.JLabel bottomUnitLabel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private java.awt.Button enterButton;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JTextArea invoiceTextArea;
    private javax.swing.JScrollPane invoiceTextContainer;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel itemQuantityLabel;
    private javax.swing.JFrame mainFrame;
    private javax.swing.JPanel mainPanel;
    private java.awt.Label nameLabel;
    private java.awt.TextField nameTextField;
    private java.awt.Button payButton;
    private javax.swing.JLabel paymentAmountLabel;
    private java.awt.TextField paymentAmountTextField;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel paymentTypeLabel;
    private java.awt.Choice paymentTypeMenu;
    private javax.swing.JLabel productLabel;
    private javax.swing.JPanel productPanel;
    private javax.swing.JLabel productQuantityLabel;
    private java.awt.Choice quantityMenu;
    private javax.swing.JLabel topExtendedPriceLabel;
    private javax.swing.JLabel topUnitLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValueLabel;
    private javax.swing.JLabel upcLabel;
    private java.awt.Choice upcMenu;
    // End of variables declaration
    //</editor-fold>

}
